[tool.ruff]
target-version = "py311"
extend-exclude = [
  ".venv", "venv", "env", "*/site-packages/*",
  ".git", ".pytest_cache", ".mypy_cache", "build", "dist", "node_modules"
]

[tool.ruff.lint]
select = ["E","F","B","I"]
extend-select = ["PL","UP","RUF"]
ignore = []